export default {
  auth: {
    failed: "احا",
    throttle: "Too many login attempts. Please try again in {seconds} seconds.",
  },
  custom: {
    Home: "الصفحه الرئيسيه",
    users: "المستخدمين",
    add_new_user: "أضافه مستخدم جديد",
    add_new_tickets: "أضافه تذكره جديده",
    edit_user: "تعديل بيانات مستخدم ",
    edit_tickets: "تعديل التذكره",
    tickets: "التذاكر",
  },
  inputs: {
    name: "الاسم",
    email: "البريد الالكتروني",
    username: "أسم المستخدم",
    password: "كلمه المرور",
    user_role: "الدور",
    choose: "اختار",
    title: "العنوان",
    description: "الوصف",
    user: "المستخدم",
    choose_image: "اختار صوره",
    image: "صوره",
  },
  buttons: {
    save: "حفظ",
    update: "تحديث",
    edit: "تعديل",
    add: "أضافه",
    delete: "حذف",
  },
  tabels: {
    users: "المستخدمين",
    user: "المستخدم",
    id: "الرقم التعريفي",
    name: "الاسم",
    email: "البريد الالكتروني",
    username: "أسم المستخدم",
    password: "كلمه المرور",
    role: "الدور",
    title: "العنوان",
    description: "الوصف",
    actions: "الاجراءات",
    status:"الحاله",
  },
};
